app/urls.py
from django.urls import path
from .views import BikeListView, BookingListView, BikeDetailView, CancelBookingView

app_name='app'

urlpatterns= [
    path('bike_list/', BikeListView, name='BikeListView'),
    path('booking_list/', BookingListView.as_view(), name='BookingListView'),
    path('bike/<model>', BikeDetailView.as_view(), name='BikeDetailView'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(), name='CancelBookingView')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

# Create your models here.

class Bike(models.Model):
    BIKE_CATEGORIES=(
        ('CUB','Underbone'),
        ('SPO','Sport'),
        ('STR','Street'),
        ('SCO','Scooter'),
    )

    BIKE_CLASS=(
        ('2B','Class 2B'),
        ('2A','Class 2A'),
        ('2','Class 2'),
    )

    BIKE_MODELS=(
        ('Aerox','Yamaha Aerox 155'),
        ('Sniper','Yamaha Sniper T150'),
        ('FZ16','Yamaha FZ16'),
        ('FZ16ST','Yamaha FZ16ST'),
        ('CB190R','Honda CB190R'),
        ('CB400 Sp2','Honda CB400 (Super 4) Spec 2'),
        ('CB400 Sp3','Honda CB400 (Super 4) Spec 3'),
    )

    plate_no = models.CharField(max_length=8, null=True)
    category = models.CharField(max_length=3, choices=BIKE_CATEGORIES, null=True)
    bike_class = models.CharField(max_length=2, choices=BIKE_CLASS, null=True)
    model = models.CharField(max_length=12, choices=BIKE_MODELS, null=True)
    
    def __str__(self):
        return f'{self.model} ({self.plate_no}) [{self.bike_class} | {self.category}]'

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bike = models.ForeignKey(Bike, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'From: {self.check_in.strftime("%d-%b-%Y %H:%M")} To: {self.check_out.strftime("%d-%b-%Y %H:%M")}'

    def get_bike_model(self):
        bike_models = dict(self.bike.BIKE_MODELS)
        bike_model = bike_models.get(self.bike.model)
        return bike_model
    
    def get_bike_category(self):
        bike_categories = dict(self.bike.BIKE_CATEGORIES)
        bike_category = bike_categories.get(self.bike.category)
        return bike_category

    def get_cancel_booking_url(self):
        return reverse_lazy('app:CancelBookingView', args=[self.pk, ])

app/forms.py
from django import forms
from datetime import datetime

class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M",] )
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M",] )

app/views.py
from django.http import request
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, FormView, View, DeleteView
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView
from .models import Bike, Booking
from .forms import AvailabilityForm
from app.booking_functions.availability import check_availability
from app.booking_functions.get_bike_model_url_list import get_bike_model_url_list
from app.booking_functions.get_bike_info_human_format import get_bike_model_human_format
from app.booking_functions.get_available_bikes import get_available_bikes
from app.booking_functions.book_bike import book_bike

# Create your views here.

def BikeListView(request):
    bike_model_url_list =  get_bike_model_url_list()
    
    context={
        "bike_list": bike_model_url_list,
    }

    return render(request, 'bike_list_view.html', context)

class BookingListView(ListView):
    model = Booking
    template_name = "booking_list_view.html"
    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list

class BikeDetailView(View):
    def get(self, request, *args, **kwargs):
        model = self.kwargs.get('model', None)
        bike_model_human_format = get_bike_model_human_format(model)
        form = AvailabilityForm()
        if bike_model_human_format is not None:
            context={
                'bike_model': bike_model_human_format,
                'form': form,
            }
            return render(request, 'bike_detail_view.html', context)
        else:
            return HttpResponse('Model does not exist.')

    def post(self, request, *args, **kwargs):
        model = self.kwargs.get('model', None)
        
        form =  AvailabilityForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

        available_bikes = get_available_bikes(model, data['check_in'], data['check_out'])

        if available_bikes is not None:
            booking = book_bike(request, available_bikes[0], data['check_in'], data['check_out'])
            return HttpResponse(booking)
        else:
            return HttpResponse("All of this model of bikes are booked for the dates you have requested! Please try another model or change the dates!")

class CancelBookingView(DeleteView):
    model = Booking
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('app:BookingListView')

app/templates/bike_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bike Details</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'app/css/bike_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Bike Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Bike Details -->
        <div class="bike">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'app:BikeListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Bike Information -->
            <div class="bike-info">
                <h1>{{bike_model}}</h1>
                <h2>{{bike_category}}</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Bike Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>
                
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Submit Booking</button>
                </div>

            </form>

        </div> <!-- END Bike Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

app/templates/bike_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TMS Leasing</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'app/css/bike_list_view.css' %}">
</head>

<body>
    <!-- Brand -->
    
    <h1 id="brand">Motorcycle Rental</h1>
    <h2 id="paragraph_title">Bikes Available For Rent</h2>
    <!-- Main Content -->
    <div class="content">
        {% for model, bike_url in bike_list %}
        <div class="bike">
            <a href="{{bike_url}}">
                <img
                    src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">

                <h2>{{model}}</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi</p>
            </a>
        </div>
        {% endfor %}



    </div>
</body>

</html>

app/templates/booking_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bike Details</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'app/css/bike_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Bike Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Bike Details -->
        <div class="bike">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'app:BikeListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Bike Information -->
            <div class="bike-info">
                <h1>{{bike_category}} Bikes</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Bike Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you want to cancel this booking?</h2>
                <h3>{{booking.get_bike_model}} [{{booking.bike.plate_no}}]</h3>
                <h3>From: {{booking.check_in}}</h3>
                <h3>To: {{booking.check_out}}</h3>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="cancel">Cancel Booking</button>
                </div>

            </form>

        </div> <!-- END Bike Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

app/templates/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'app/css/booking_list_view.css' %}">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome, {{user}}!</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="{% url 'app:BikeListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for booking in booking_list %}
            <div class="booking">
                <img src="https://images.unsplash.com/photo-1560067174-c5a3a8f37060?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80"
                    alt="">
                <div class="model">
                    <h2>{{booking.get_bike_model}}</h2>
                </div>
                <div class="bike_class">
                    <h3>Class {{booking.bike.bike_class}}</h3>
                </div>
                <div class="bike_category">
                    <h3>Category: {{booking.get_bike_category}} Bike</h3>
                </div>
                <div class="from">
                    <h3>From: {{booking.check_in}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{booking.check_out}}</h3>
                </div>
                <div class="cancel"><a href="{{booking.get_cancel_booking_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>
</body>

</html>